### ISSUE TITLE
请问一下javaweb是看的谁的课，可以分享一下md文件里面提到的资料吗？

### ISSUE THREAD

**Issue by Everythingismetaphor** [JERRY-Z-J-R/I-love-you-3-thousand#12]

**Comment by JERRY-Z-J-R** [comment]
JavaWeb：【黑马程序员新版JavaWeb基础教程，Java web从入门到企业实战完整版】 https://www.bilibili.com/video/BV1Qf4y1T7Hx/?share_source=copy_web&vd_source=f142a37c45de7b8323eedf220d9dcdd1
